// <auto-generated />
using System;
using GoPickup.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoPickup.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260827161358_InicialCompleta")]
    partial class InicialCompleta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoPickup.API.Models.CodigoVerificacionTelefono", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVerificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Intentos")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Verificado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CodigosVerificacionTelefono");
                });

            modelBuilder.Entity("GoPickup.API.Models.Conductor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CalificacionPromedio")
                        .HasColumnType("float");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("EstadoSolicitud")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoLicenciaFrontalUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TipoLicencia")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaActualizacionUbicacion")
                        .HasColumnType("datetime2");

                    b.Property<double?>("UltimaLatitud")
                        .HasColumnType("float");

                    b.Property<double?>("UltimaLongitud")
                        .HasColumnType("float");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Conductores");
                });

            modelBuilder.Entity("GoPickup.API.Models.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CalificacionCliente")
                        .HasColumnType("int");

                    b.Property<int?>("CalificacionConductor")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("ConductorId")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionCarga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinoDireccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DestinoLatitud")
                        .HasColumnType("float");

                    b.Property<double>("DestinoLongitud")
                        .HasColumnType("float");

                    b.Property<double?>("DistanciaKm")
                        .HasColumnType("float");

                    b.Property<int?>("DuracionEstimadaMin")
                        .HasColumnType("int");

                    b.Property<bool>("EsInterprovincial")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAceptacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LlevaCarga")
                        .HasColumnType("bit");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("int");

                    b.Property<string>("MotivoCancelacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NotificadoLlegada")
                        .HasColumnType("bit");

                    b.Property<string>("OrigenDireccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OrigenLatitud")
                        .HasColumnType("float");

                    b.Property<double>("OrigenLongitud")
                        .HasColumnType("float");

                    b.Property<decimal?>("RecargoAplicado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TarifaAcordada")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TarifaFinal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TarifaPropuestaCliente")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TarifaSugerida")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TipoCamionetaRequerida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ConductorId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("GoPickup.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoPerfilUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("RecargoPendiente")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("TelefonoVerificado")
                        .HasColumnType("bit");

                    b.Property<string>("TokenPushNotificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GoPickup.API.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ConductorId")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionCapacidad")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FotoCabinaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoFrontalUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoLateralUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TipoCamioneta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConductorId")
                        .IsUnique();

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("GoPickup.API.Models.Conductor", b =>
                {
                    b.HasOne("GoPickup.API.Models.Usuario", "Usuario")
                        .WithOne("PerfilConductor")
                        .HasForeignKey("GoPickup.API.Models.Conductor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GoPickup.API.Models.Solicitud", b =>
                {
                    b.HasOne("GoPickup.API.Models.Usuario", "Cliente")
                        .WithMany("SolicitudesComoCliente")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoPickup.API.Models.Conductor", "Conductor")
                        .WithMany("SolicitudesComoConductor")
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Conductor");
                });

            modelBuilder.Entity("GoPickup.API.Models.Vehiculo", b =>
                {
                    b.HasOne("GoPickup.API.Models.Conductor", "Conductor")
                        .WithOne("Vehiculo")
                        .HasForeignKey("GoPickup.API.Models.Vehiculo", "ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conductor");
                });

            modelBuilder.Entity("GoPickup.API.Models.Conductor", b =>
                {
                    b.Navigation("SolicitudesComoConductor");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("GoPickup.API.Models.Usuario", b =>
                {
                    b.Navigation("PerfilConductor");

                    b.Navigation("SolicitudesComoCliente");
                });
#pragma warning restore 612, 618
        }
    }
}
